# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
#    serializer_listener.posts:
#        class: AppBundle\Serializer\Listener\PostListener
#        tags:
#            - { name: jms_serializer.event_subsciber }
#    serializer_handler.post:
#        class: AppBundle\Serializer\Handler\PostHandler
#        tags:
#            - { name: jms_serializer.subscribing_handler }